# introduction to numpy

In [1]:
#numpy,stands for numerical python
import numpy as np

In [6]:
inp=(20,41,53,12,25)
print(inp)
print(type(inp))
abc=np.array(inp)
print(abc)
print(type(abc))
print(abc.shape)
abc.ndim #to check the dimension

(20, 41, 53, 12, 25)
<class 'tuple'>
[20 41 53 12 25]
<class 'numpy.ndarray'>
(5,)


1

In [3]:
#nd=n dimensional

In [9]:
#create a seq num in array
sq=np.arange(9)
print(sq)
print(sq.ndim)
print(sq.shape)

[0 1 2 3 4 5 6 7 8]
1
(9,)


In [11]:
print(sq.itemsize) #print the length of one array element in bytes
sq.astype(float)

4


array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [13]:
np.linspace(1,5,num=4) # if we dont provide any number it will by default take 50 number

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [16]:
np.linspace(1,5,num=5,endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [22]:
lis=[32,78,79,73]
ara=np.array(lis)
print(ara)
#(0°C × 9/5) + 32
bca=(ara*(9/5))+32
print(bca)
fvalues=[x*9/5 + 32 for x in lis]
print(fvalues)

[32 78 79 73]
[ 89.6 172.4 174.2 163.4]
[89.6, 172.4, 174.2, 163.4]


In [24]:
sq=np.arange(24)
print(sq)
b=sq.reshape(2,4,3) #2 matrix, 4 row, 3 column
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [28]:
sq=np.arange(32)
b=sq.reshape(8,4)
print(b)
c=sq.reshape(2,4,4)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]


In [30]:
a=np.arange(12)
a=a.reshape(3,4)
b=np.arange(12)
b=b.reshape(3,4)
c=a+b
print(c)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [33]:
array1=np.array([[1,2,3,12],[4,5,6,11],[7,8,9,10]])
array2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1+array2)

ValueError: operands could not be broadcast together with shapes (3,4) (3,3) 

In [40]:
x=np.ones([3,4],dtype=int) #use dtype to specify the data type such as int,float and string
print(x)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [59]:
x=np.random.random((3,3))
y=np.ones((3,4))
x*y

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [35]:
y=np.random.random((3,4))
print(y)

[[0.06448505 0.59765536 0.24410647 0.23262344]
 [0.78943761 0.4084844  0.06657097 0.93540953]
 [0.65245612 0.55452117 0.05501276 0.59167847]]


In [64]:
data=np.array([10,2,4,5,7,14,22])
print(data.mean())
print(data.min())
print(data.max())
print(np.median(data))
print(np.std(data))

9.142857142857142
2
22
7.0
6.423807758833462


In [65]:
#dor product
f=np.array([1,2])
g=np.array([4,5])
print("f",f)
print("g",g)
np.dot(f,g)

f [1 2]
g [4 5]


14

In [67]:
a=np.array([1,2,3,4,5],ndmin=2)
print(a)
print(a.shape)

[[1 2 3 4 5]]
(1, 5)


In [70]:
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [77]:
lst=[[30000,8.7,9.9],[1.1,7.8,0.7]]
A=np.array(lst,dtype=np.int16)
print(A)

[[3.0e+04 8.7e+00 9.9e+00]
 [1.1e+00 7.8e+00 7.0e-01]]


In [78]:
student=np.dtype([("name","S30"),("age","i4"),("marks","f4")])
a=np.array([("abc",21,50),("xyz",18,75)],dtype=student)
print(a)
print(a["name"])

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]
[b'abc' b'xyz']


In [89]:
a=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print("the items in the second column are")
print(a[:,1])
print("the items in the second row are")
print(a[1,:])
print("the items column 1 onwards are")
print(a[:,1:])
print("the items row 1 onwards are")
print(a[1:,:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
the items in the second column are
[2 4 5]
the items in the second row are
[3 4 5]
the items column 1 onwards are
[[2 3]
 [4 5]
 [5 6]]
the items row 1 onwards are
[[3 4 5]
 [4 5 6]]


In [90]:
a=np.array([[1,2],[3,4]])
b=np.array([1,2])
print("matrix a:")
print(a)
print("matrix b:")
print(b)
print("multiplication with broadcasting:")
print(a*b)
print("addition with broadcasting:")
print(a+b)

matrix a:
[[1 2]
 [3 4]]
matrix b:
[1 2]
multiplication with broadcasting:
[[1 4]
 [3 8]]
addition with broadcasting:
[[2 4]
 [4 6]]


In [91]:
f=np.array([1,2,3])
g=np.array([4,5,6])

print("horizontal append:",np.hstack((f,g)))
print("vertical append:",np.vstack((f,g)))

horizontal append: [1 2 3 4 5 6]
vertical append: [[1 2 3]
 [4 5 6]]


In [93]:
c=np.array([[1,2,3],[4,5,6]])
c.flatten()

array([1, 2, 3, 4, 5, 6])